version: '3'
services:
    app:
        build: ./docker/php/
        container_name: app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - server

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        container_name: nginx
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - server

    database:
        build: ./docker/mysql
        container_name: mysql
        restart: always
        tty: true
        environment:
            MYSQL_DATABASE: 'app'
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql/.dbdata:/var/lib/mysql
        networks:
            - server

networks:
    server:
        driver: bridge




